

version: '3.1'

services:
  mazadataapp:
    container_name: mazadataapp
    build: .
    volumes:
      - .:/mazadatemasr
    depends_on:
      - mongo
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_USERNAME=root
      - DB_PASSWORD=example
      - DB_NAME=mazadata
    ports:
      - 9000:9000
    env_file:
      - ./.env  

  mongo:
    image: mongo
    restart: always
    # command: ["mongod", "--config", "/etc/mongod.conf"]

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - ./mongod.conf:/etc/mongod.conf
    # command: ["mongod", "--replSet", "rs0"]
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8888:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  mongo-data:
